const ALLOWED_VALIDATION_SCHEMA_SCOPES = {
  BODY: "BODY",
  PARAMS: "PARAMS",
  QUERY: "QUERY",
  NONE: "NONE",
};

const ALLOWED_VALID_DAYS = [
  "MONDAY",
  "TUESDAY",
  "WEDNESDAY",
  "THURSDAY",
  "FRIDAY",
  "SATURDAY",
  "SUNDAY",
];

module.exports = {
  ALLOWED_VALIDATION_SCHEMA_SCOPES,
  ALLOWED_VALID_DAYS,
};
